### PR TITLE
Installation instructions for macOS.

### PR DESCRIPTION
**Pull request by maxkatzmann**
Added instructions about how to build the project on macOS.

### CODE REVIEW

**Comment by chistopher** [comment]
On macOS the default OpenMP should be found by cmake since version 3.12 [see here](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1812). Maybe we have to change the way omp is linked as shown in this [post](https://iscinumpy.gitlab.io/post/omp-on-high-sierra/). Eventually this will be the cleanest solution. I just hope this does not break it for the other operating systems. I will have a look at the current travis failure for GCC next week. Could you check if the cmake 3.12 way works for you?

**Comment by maxkatzmann** [comment]
Don't they [confirm](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1812#note_381724) that OpenMP is not supported by Apple Clang, i.e., there is no default OpenMP and brew or similar is needed?

I saw the other post as well. The command `$(brew --prefix libomp)` does indeed lead to the current version of OpenMP installed by brew. Maybe this can be used to tell CMake to pass the corresponding flags (that I added to the readme) when building for macOS?

**Comment by chistopher** [comment]
If you don't have cmake 3.12 or newer, you could try to add your omp installation to the CMAKE_PREFIX_PATH environment variable

**Comment by maxkatzmann** [comment]
I have CMake 3.17.0. However, when making, it is unable to find the omp headers. Setting the CMAKE_PREFIX_PATH environment variable does not help.

**Comment by chistopher** [comment]
To clear some of your answers up:
Yes, apple clang does not support OMP, but as they say, they have not removed it either.
Anyway, the 'hack' to use OMP with apple clang is part of cmake since 3.12.
Also the brew openMP is the default openMP for macOS.

I think the problem is related to [this](https://gitlab.kitware.com/cmake/cmake/-/issues/19180) and [this](https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html).
When using the old way of linking against OMP like this `${OpenMP_CXX_FLAGS}` we only set the compiler flags needed to compile with OMP and assume that omp is found in the system include and link path. This works for me but apparently there are some problems for macOS with system paths and `/usr/local/` where brew installs stuff. This should be fixed however, when linking against `OpenMP::OpenMP_CXX` instead of the flags. This is the correct/modern way to link against libs because it should handle stuff like include paths and lib names internally. For OMP it seems to be supported by cmake since 3.9. I am fine with updating the required CMake version for this.
It should also clean up some code for us like `$<$<NOT:$<CXX_COMPILER_ID:MSVC>>:${OpenMP_CXX_FLAGS}>` (all but MCSV need linker+compiler flags for OMP, MSVC needs only compiler flags.)

Do you want to make the change? Otherwise I try to do it next week.

PS: cross plattform development is always kinda messy.

**Comment by chistopher** [comment]
Sorry for the `PREFIX_PATH` stuff. That should only be relevant when the `find_package` call fails.

**Comment by maxkatzmann** [comment]
Since I am not familiar with CMake, I think it would save both of us time, if you tried to fix it sometime next week. I'd be happy to test and report on proposed fixes though.

**Pull request closed without merging**
